export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { Inter } from "next/font/google"
const inter = Inter({subsets: ["latin"]});
import "./globals.css"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-light`}>{children}</body>
    </html>
  )
}
