export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex w-full items-center pt-3">
      <div className="flex-[2]"></div>
      <div className="flex-[3]">{children}</div>
      <div className="flex-[2]"></div>
    </div>
  );
}
